// USER_REGISTER
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'
// USER_LOGIN
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGIN_RESET='USER_LOGIN_RESET'
// IMAGE 
export const USER_IMAGE_REQUEST='USER_IMAGE_REQUEST'
export const USER_IMAGE_SUCCESS='USER_IMAGE_SUCCESS'
export const USER_IMAGE_FAIL='USER_IMAGE_FAIL'
export const USER_IMAGE_RESET='USER_IMAGE_RESET'
